language: c
 
env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.8.0"
 
before_install:
 - sudo apt-get install mono-devel mono-gmcs nunit-console
 - mozroots --import --sync
 
script:
  - xbuild ./src/xbuild.xml
 # - .ci/nunit.sh Tests/bin/Debug/Tests.dll
  - nunit-console ./src/NetAspect.Weaver.Tests/bin/Debug/NetAspect.Weaver.Tests.dll