# Site settings
title: NetAspect
email: Arnud.Sylvestre@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arnaudsylvestre.github.io/fluentaspect.com" # the base hostname & protocol for your site
github_username:  arnaudsylvestre

# Build settings
markdown: kramdown