//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetAspect.Doc.Builder.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetAspect.Doc.Builder.Templates.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $documentation.Header
        ///
        ///&lt;div class=&quot;container bs-docs-container&quot;&gt;
        ///      &lt;div class=&quot;row&quot;&gt;
        ///      &lt;div class=&quot;col-md-12&quot; role=&quot;main&quot;&gt;
        ///
        ///$documentation.Basics
        ///
        ///         &lt;div class=&quot;bs-docs-section&quot;&gt;
        ///            &lt;div class=&quot;page-header&quot;&gt;
        ///               &lt;h1 id=&quot;dropdowns&quot;&gt;Interceptors&lt;/h1&gt;
        ///            &lt;/div&gt;
        ///			&lt;p&gt;In NetAspect, an interceptor is a method which will be called on &lt;/p&gt;
        ///			&lt;h2 id=&quot;dropdowns&quot;&gt;For method weaving&lt;/h2&gt;
        ///            &lt;p&gt;The &quot;method weaving&quot; will modify the code of the method to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $documentation.Header
        ///
        ///&lt;div class=&quot;container bs-docs-container&quot;&gt;
        ///      &lt;div class=&quot;row&quot;&gt;
        ///      &lt;div class=&quot;col-md-12&quot; role=&quot;main&quot;&gt;
        ///
        ///$documentation.Basics
        ///
        ///         &lt;div class=&quot;bs-docs-section&quot;&gt;
        ///            &lt;div class=&quot;page-header&quot;&gt;
        ///               &lt;h1 id=&quot;dropdowns&quot;&gt;Interceptors&lt;/h1&gt;
        ///            &lt;/div&gt;
        ///			&lt;p&gt;In NetAspect, an interceptor is a method which will be called &lt;/p&gt;
        ///			&lt;h2 id=&quot;dropdowns&quot;&gt;For method weaving&lt;/h2&gt;
        ///            &lt;p&gt;The &quot;method weaving&quot; will modify the code of the method to ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocumentationPage {
            get {
                return ResourceManager.GetString("DocumentationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $documentation.Header
        ///
        ///&lt;div class=&quot;container bs-docs-container&quot;&gt;
        ///      &lt;div class=&quot;row&quot;&gt;
        ///      &lt;div class=&quot;col-md-12&quot; role=&quot;main&quot;&gt;
        ///
        ///$documentation.Basics
        ///
        ///         &lt;div class=&quot;bs-docs-section&quot;&gt;
        ///            &lt;div class=&quot;page-header&quot;&gt;
        ///               &lt;h1 id=&quot;dropdowns&quot;&gt;Interceptors&lt;/h1&gt;
        ///            &lt;/div&gt;
        ///			&lt;p&gt;In NetAspect, an interceptor is a method which will be called &lt;/p&gt;
        ///			&lt;h2 id=&quot;dropdowns&quot;&gt;For method weaving&lt;/h2&gt;
        ///            &lt;p&gt;The &quot;method weaving&quot; will modify the code of the method to ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GettingStartedPage {
            get {
                return ResourceManager.GetString("GettingStartedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $documentation.Header
        ///
        ///&lt;div class=&quot;container bs-docs-container&quot;&gt;
        ///      &lt;div class=&quot;row&quot;&gt;
        ///      &lt;div class=&quot;col-md-12&quot; role=&quot;main&quot;&gt;
        ///
        ///$documentation.Basics
        ///
        ///         &lt;div class=&quot;bs-docs-section&quot;&gt;
        ///            &lt;div class=&quot;page-header&quot;&gt;
        ///               &lt;h1 id=&quot;dropdowns&quot;&gt;Interceptors&lt;/h1&gt;
        ///            &lt;/div&gt;
        ///			&lt;p&gt;In NetAspect, an interceptor is a method which will be called &lt;/p&gt;
        ///			&lt;h2 id=&quot;dropdowns&quot;&gt;For method weaving&lt;/h2&gt;
        ///            &lt;p&gt;The &quot;method weaving&quot; will modify the code of the method to ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///   &lt;head&gt;
        ///      &lt;meta charset=&quot;utf-8&quot;&gt;
        ///      &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///      &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///      &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///      &lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///      &lt;link rel=&quot;shortcut icon&quot; href=&quot;../../docs-assets/ico/favicon.png&quot;&gt;
        ///      &lt;title&gt;NetAspect&lt;/title&gt;
        ///      &lt;link href=&quot;bootstrap-3.0.2/dist/css/bootstrap.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///      &lt;link href=&quot;jumbotron.cs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
    }
}
