//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetAspect.Doc.Builder.Templates {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetAspect.Doc.Builder.Templates.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à $documentation.Header
        ///
        ///&lt;div class=&quot;container bs-docs-container&quot;&gt;
        ///      &lt;div class=&quot;row&quot;&gt;
        ///      &lt;div class=&quot;col-md-12&quot; role=&quot;main&quot;&gt;
        ///
        ///$documentation.Basics
        ///
        ///      &lt;!-- 
        ///================================================	  
        ///	  Weaving
        ///================================================
        ///	  --&gt;
        ///         &lt;div class=&quot;bs-docs-section&quot;&gt;
        ///            &lt;div class=&quot;page-header&quot;&gt;
        ///               &lt;h1 id=&quot;dropdowns&quot;&gt;Weaving&lt;/h1&gt;
        ///            &lt;/div&gt;
        ///$documentation.MethodWeaving
        ///$documentation.MethodWeavingPossibil [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;input type=&quot;button&quot; class=&quot;btn btn-primary&quot; data-toggle=&quot;collapse&quot; data-target=&quot;#MethodWeavingPossibilities&quot; value=&quot;Show possibilities&quot;&gt;
        ///    &lt;!-- Collapsible Element HTML --&gt;
        ///    &lt;div id=&quot;MethodWeavingPossibilities&quot; class=&quot;collapse&quot;&gt;
        ///
        ///
        ///
        ///#foreach ($possibility in $documentation.Possibilities)
        ///
        ///&lt;!-- 
        ///================================================	  
        ///	  $possibility.Kind possibilities
        ///================================================
        ///	  --&gt;
        ///
        ///	&lt;h4 id=&quot;dropdowns-example&quot;&gt;$possibility.Title&lt;/h4&gt;
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string InstructionWeavingPossibilities {
            get {
                return ResourceManager.GetString("InstructionWeavingPossibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;input type=&quot;button&quot; class=&quot;btn btn-primary&quot; data-toggle=&quot;collapse&quot; data-target=&quot;#MethodWeavingPossibilities&quot; value=&quot;Show possibilities&quot;&gt;
        ///    &lt;!-- Collapsible Element HTML --&gt;
        ///    &lt;div id=&quot;MethodWeavingPossibilities&quot; class=&quot;collapse&quot;&gt;
        ///
        ///
        ///
        ///#foreach ($possibility in $documentation.Possibilities)
        ///
        ///&lt;!-- 
        ///================================================	  
        ///	  $possibility.Kind possibilities
        ///================================================
        ///	  --&gt;
        ///
        ///	&lt;h4 id=&quot;dropdowns-example&quot;&gt;$possibility.Title&lt;/h4&gt;
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string WeavingPossibilities {
            get {
                return ResourceManager.GetString("WeavingPossibilities", resourceCulture);
            }
        }
    }
}
