//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetAspect.Doc.Builder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetAspect.Doc.Builder.Resources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;bs-docs-section&quot;&gt;
        ///		 
        ///      &lt;!-- 
        ///================================================	  
        ///	  Basics
        ///================================================
        ///	  --&gt;
        ///		 
        ///            &lt;div class=&quot;page-header&quot;&gt;
        ///               &lt;h1 id=&quot;attributes&quot;&gt;Basics&lt;/h1&gt;
        ///            &lt;/div&gt;
        ///            &lt;h3 id=&quot;dropdowns-example&quot;&gt;The sample class&lt;/h3&gt;
        ///            &lt;p&gt;Imagine that we want to log the different access on the following class : &lt;/p&gt;
        ///            &lt;pre class=&quot;prettyprint&quot;&gt;
        ///public class MyInt
        ///{
        ///   int val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Basics {
            get {
                return ResourceManager.GetString("Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DocumentationConfiguration xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;InterceptorKinds&gt;
        ///    &lt;InterceptorKindConfiguration&gt;
        ///      &lt;Parameters&gt;
        ///        &lt;ParameterConfiguration&gt;
        ///          &lt;Name&gt;name&lt;/Name&gt;
        ///          &lt;Description&gt;description&lt;/Description&gt;
        ///        &lt;/ParameterConfiguration&gt;
        ///      &lt;/Parameters&gt;
        ///      &lt;Interceptors&gt;
        ///        &lt;InterceptorConfiguration&gt;
        ///          &lt;MethodName&gt;Method&lt;/MethodName&gt;
        ///          &lt;W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocumentationPage {
            get {
                return ResourceManager.GetString("DocumentationPage", resourceCulture);
            }
        }
    }
}
