//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetAspect.Doc.Builder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetAspect.Doc.Builder.Resources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;bs-docs-section&quot;&gt;
        ///		 
        ///      &lt;!-- 
        ///================================================	  
        ///	  Basics
        ///================================================
        ///	  --&gt;
        ///		 
        ///            &lt;div class=&quot;page-header&quot;&gt;
        ///               &lt;h1 id=&quot;attributes&quot;&gt;Basics&lt;/h1&gt;
        ///            &lt;/div&gt;
        ///            &lt;h3 id=&quot;dropdowns-example&quot;&gt;The sample class&lt;/h3&gt;
        ///            &lt;p&gt;Imagine that we want to log the different access on the following class : &lt;/p&gt;
        ///            &lt;pre class=&quot;prettyprint&quot;&gt;
        ///public class MyInt
        ///{
        ///   int val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Basics {
            get {
                return ResourceManager.GetString("Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///   &lt;head&gt;
        ///      &lt;meta charset=&quot;utf-8&quot;&gt;
        ///      &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///      &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///      &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///      &lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///      &lt;link rel=&quot;shortcut icon&quot; href=&quot;../../docs-assets/ico/favicon.png&quot;&gt;
        ///      &lt;title&gt;NetAspect&lt;/title&gt;
        ///      &lt;link href=&quot;bootstrap-3.0.2/dist/css/bootstrap.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///      &lt;link href=&quot;jumbotron.cs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 id=&quot;dropdowns&quot;&gt;Method Weaving&lt;/h2&gt;
        ///            &lt;p&gt;The &quot;method weaving&quot; will modify the code of the method to add behavior. It is possible to add behavior :&lt;/p&gt;
        ///            &lt;ul&gt;
        ///               &lt;li&gt;&lt;b&gt;Before&lt;/b&gt; the method is executed&lt;/li&gt;
        ///               &lt;li&gt;&lt;b&gt;After&lt;/b&gt; the method is executed when no exception is raised&lt;/li&gt;
        ///               &lt;li&gt;&lt;b&gt;When exception occurs&lt;/b&gt; in the method&lt;/li&gt;
        ///               &lt;li&gt;&lt;b&gt;On finally&lt;/b&gt; : at the end of the method when an exception is raised or not&lt;/li&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodWeaving {
            get {
                return ResourceManager.GetString("MethodWeaving", resourceCulture);
            }
        }
    }
}
